### ISSUE TITLE
Typescript checker not working on "JwtModule.registerAsync" when using "useFactory"

### ISSUE THREAD

**Issue by mazyvan** [nestjs/jwt#20]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

Type checker not working on `JwtModule.registerAsync` when using `useFactory` funcition.

![image](https://user-images.githubusercontent.com/10915753/53751000-e1f99400-3e70-11e9-8647-c6c8460bea6e.png)

It's wired because I check the type and It is correct.

![image](https://user-images.githubusercontent.com/10915753/53751203-664c1700-3e71-11e9-9a45-e783cfec5960.png)

Also there is any issue on that file.

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

Also I know this is not the place for this but...  
Nest such is a really great project. I love it ❤ I would like to contribute on anything if posible. 
Time ago I wanted to create some framework in typescript in witch you could return promises and throw exceptions instead of using the `res` object. But then I check this project and It's just like my dream come true.

So if there´s anything I can do please tell me. From pull requests to docs contribution 👍

**Comment by kamilmysliwiec** [comment]
> Nest such is a really great project. I love it ❤ I would like to contribute on anything if posible.
Time ago I wanted to create some framework in typescript in witch you could return promises and throw exceptions instead of using the res object. But then I check this project and It's just like my dream come true.

I'm glad you like it :) 

Here you can find the contribution guide: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
Also, here is a docs repo: https://github.com/nestjs/docs.nestjs.com (the entire documentation is written in markdown syntax, it should be pretty easy to contribute)

Contributions are always welcome!

Regarding your issue, I don't know how we can help.. As you pointed out, file itself seems to be correct.
